name: Update Badge

on:
  workflow_dispatch:
    inputs:
      text:
        description: "バッジのテキスト"
        required: true
        default: "status"
      message:
        description: "バッジのメッセージ"
        required: true
        default: "success"
      color:
        description: "バッジの色"
        required: true
        default: "brightgreen"
        type: choice
        options:
          - brightgreen
          - red
          - yellow
          - blue
          - green
      style:
        description: "バッジのスタイル"
        required: true
        default: "flat"
        type: choice
        options:
          - flat
          - flat-square
          - plastic
          - for-the-badge
          - social

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download badge from shields.io
        run: |
          mkdir -p badges
          # URLエンコード
          TEXT=$(echo "${{ github.event.inputs.text }}" | sed 's/ /_/g')
          MESSAGE=$(echo "${{ github.event.inputs.message }}" | sed 's/ /_/g')

          # shields.ioからバッジをダウンロード
          curl -o badges/status.svg \
            "https://img.shields.io/badge/$TEXT-$MESSAGE-${{ github.event.inputs.color }}?style=${{ github.event.inputs.style }}"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./badges
